DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
DROP TABLE JOB;
DROP TABLE LOCATION;
DROP TABLE NATIONAL;
DROP TABLE SAL_GRADE;

--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------
CREATE TABLE DEPARTMENT 
(
    DEPT_ID CHAR(2 BYTE) PRIMARY KEY, 
    DEPT_TITLE VARCHAR2(35 BYTE) NOT NULL, 
    LOCATION_ID CHAR(2 BYTE) NOT NULL
);

COMMENT ON COLUMN DEPARTMENT.DEPT_ID IS '�μ��ڵ�';
COMMENT ON COLUMN DEPARTMENT.DEPT_TITLE IS '�μ���';
COMMENT ON COLUMN DEPARTMENT.LOCATION_ID IS '�����ڵ�';
COMMENT ON TABLE DEPARTMENT IS '�μ�';

INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D1','�λ������','L1');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D2','ȸ�������','L1');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D3','�����ú�','L1');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D4','����������','L1');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D5','�ؿܿ���1��','L2');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D6','�ؿܿ���2��','L3');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D7','�ؿܿ���3��','L4');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D8','���������','L5');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D9','�ѹ���','L1');

--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------
CREATE TABLE EMPLOYEE 
(
    EMP_ID VARCHAR2(3 BYTE) PRIMARY KEY, 
    EMP_NAME VARCHAR2(20 BYTE) NOT NULL, 
    EMP_NO CHAR(14 BYTE) NOT NULL, 
    EMAIL VARCHAR2(25 BYTE), 
    PHONE VARCHAR2(12 BYTE), 
    DEPT_CODE CHAR(2 BYTE), 
    JOB_CODE CHAR(2 BYTE) NOT NULL, 
    SALARY NUMBER, 
    BONUS NUMBER, 
    MANAGER_ID VARCHAR2(3 BYTE), 
    HIRE_DATE DATE, 
    ENT_DATE DATE, 
    ENT_YN CHAR(1 BYTE) DEFAULT 'N'
);

COMMENT ON COLUMN EMPLOYEE.EMP_ID IS '�����ȣ';
COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '������';
COMMENT ON COLUMN EMPLOYEE.EMP_NO IS '�ֹε�Ϲ�ȣ';
COMMENT ON COLUMN EMPLOYEE.EMAIL IS '�̸���';
COMMENT ON COLUMN EMPLOYEE.PHONE IS '��ȭ��ȣ';
COMMENT ON COLUMN EMPLOYEE.DEPT_CODE IS '�μ��ڵ�';
COMMENT ON COLUMN EMPLOYEE.JOB_CODE IS '�����ڵ�';
COMMENT ON COLUMN EMPLOYEE.SALARY IS '�޿�';
COMMENT ON COLUMN EMPLOYEE.BONUS IS '���ʽ���';
COMMENT ON COLUMN EMPLOYEE.MANAGER_ID IS '�����ڻ��';
COMMENT ON COLUMN EMPLOYEE.HIRE_DATE IS '�Ի���';
COMMENT ON COLUMN EMPLOYEE.ENT_DATE IS '�����';
COMMENT ON COLUMN EMPLOYEE.ENT_YN IS '��������';

INSERT INTO C##SERVER.EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, DEPT_CODE, JOB_CODE, SALARY, BONUS, MANAGER_ID, HIRE_DATE, ENT_DATE, ENT_YN)
VALUES ('200','������','621235-1985634','sun_di@KH.or.kr','01099546325','D9','J1',8000000,0.3,NULL,TO_DATE('1990-02-06','YYYY-MM-DD'),NULL,'N');

-- �߰� EMPLOYEE ������ ���� ���� (���� ������ ������� ����)

--------------------------------------------------------
--  DDL for Table JOB
--------------------------------------------------------
CREATE TABLE JOB 
(
    JOB_CODE CHAR(2 BYTE) PRIMARY KEY, 
    JOB_NAME VARCHAR2(35 BYTE) NOT NULL
);

COMMENT ON COLUMN JOB.JOB_CODE IS '�����ڵ�';
COMMENT ON COLUMN JOB.JOB_NAME IS '���޸�';
COMMENT ON TABLE JOB IS '����';

INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J1','��ǥ');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J2','�λ���');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J3','����');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J4','����');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J5','����');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J6','�븮');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J7','���');

--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------
CREATE TABLE LOCATION 
(
    LOCAL_CODE CHAR(2 BYTE) PRIMARY KEY, 
    NATIONAL_CODE CHAR(2 BYTE) NOT NULL, 
    LOCAL_NAME VARCHAR2(40 BYTE) NOT NULL
);

COMMENT ON COLUMN LOCATION.LOCAL_CODE IS '�����ڵ�';
COMMENT ON COLUMN LOCATION.NATIONAL_CODE IS '�����ڵ�';
COMMENT ON COLUMN LOCATION.LOCAL_NAME IS '������';
COMMENT ON TABLE LOCATION IS '����';

INSERT INTO C##SERVER.LOCATION (LOCAL_CODE, NATIONAL_CODE, LOCAL_NAME) VALUES ('L1','KO','ASIA1');
-- �߰� LOCATION ������ ���� ����

--------------------------------------------------------
--  DDL for Table NATIONAL
--------------------------------------------------------
CREATE TABLE NATIONAL 
(
    NATIONAL_CODE CHAR(2 BYTE) PRIMARY KEY, 
    NATIONAL_NAME VARCHAR2(35 BYTE) NOT NULL
);

COMMENT ON COLUMN NATIONAL.NATIONAL_CODE IS '�����ڵ�';
COMMENT ON COLUMN NATIONAL.NATIONAL_NAME IS '������';
COMMENT ON TABLE NATIONAL IS '����';

INSERT INTO C##SERVER.NATIONAL (NATIONAL_CODE, NATIONAL_NAME) VALUES ('KO','�ѱ�');
-- �߰� NATIONAL ������ ���� ����

--------------------------------------------------------
--  DDL for Table SAL_GRADE
--------------------------------------------------------
CREATE TABLE SAL_GRADE 
(
    SAL_LEVEL CHAR(2 BYTE) PRIMARY KEY, 
    MIN_SAL NUMBER NOT NULL, 
    MAX_SAL NUMBER NOT NULL
);

COMMENT ON COLUMN SAL_GRADE.SAL_LEVEL IS '�޿����';
COMMENT ON COLUMN SAL_GRADE.MIN_SAL IS '�ּұ޿�';
COMMENT ON COLUMN SAL_GRADE.MAX_SAL IS '�ִ�޿�';
COMMENT ON TABLE SAL_GRADE IS '�޿����';

INSERT INTO C##SERVER.SAL_GRADE (SAL_LEVEL, MIN_SAL, MAX_SAL) VALUES ('S1',6000000,10000000);
-- �߰� SAL_GRADE ������ ���� ����

COMMIT;