DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
DROP TABLE JOB;
DROP TABLE LOCATION;
DROP TABLE NATIONAL;
DROP TABLE SAL_GRADE;

--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------
CREATE TABLE DEPARTMENT 
(
    DEPT_ID CHAR(2 BYTE) PRIMARY KEY, 
    DEPT_TITLE VARCHAR2(35 BYTE) NOT NULL, 
    LOCATION_ID CHAR(2 BYTE) NOT NULL
);

COMMENT ON COLUMN DEPARTMENT.DEPT_ID IS '부서코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_TITLE IS '부서명';
COMMENT ON COLUMN DEPARTMENT.LOCATION_ID IS '지역코드';
COMMENT ON TABLE DEPARTMENT IS '부서';

INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D1','인사관리부','L1');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D2','회계관리부','L1');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D3','마케팅부','L1');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D4','국내영업부','L1');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D5','해외영업1부','L2');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D6','해외영업2부','L3');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D7','해외영업3부','L4');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D8','기술지원부','L5');
INSERT INTO C##SERVER.DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID) VALUES ('D9','총무부','L1');

--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------
CREATE TABLE EMPLOYEE 
(
    EMP_ID VARCHAR2(3 BYTE) PRIMARY KEY, 
    EMP_NAME VARCHAR2(20 BYTE) NOT NULL, 
    EMP_NO CHAR(14 BYTE) NOT NULL, 
    EMAIL VARCHAR2(25 BYTE), 
    PHONE VARCHAR2(12 BYTE), 
    DEPT_CODE CHAR(2 BYTE), 
    JOB_CODE CHAR(2 BYTE) NOT NULL, 
    SALARY NUMBER, 
    BONUS NUMBER, 
    MANAGER_ID VARCHAR2(3 BYTE), 
    HIRE_DATE DATE, 
    ENT_DATE DATE, 
    ENT_YN CHAR(1 BYTE) DEFAULT 'N'
);

COMMENT ON COLUMN EMPLOYEE.EMP_ID IS '사원번호';
COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '직원명';
COMMENT ON COLUMN EMPLOYEE.EMP_NO IS '주민등록번호';
COMMENT ON COLUMN EMPLOYEE.EMAIL IS '이메일';
COMMENT ON COLUMN EMPLOYEE.PHONE IS '전화번호';
COMMENT ON COLUMN EMPLOYEE.DEPT_CODE IS '부서코드';
COMMENT ON COLUMN EMPLOYEE.JOB_CODE IS '직급코드';
COMMENT ON COLUMN EMPLOYEE.SALARY IS '급여';
COMMENT ON COLUMN EMPLOYEE.BONUS IS '보너스율';
COMMENT ON COLUMN EMPLOYEE.MANAGER_ID IS '관리자사번';
COMMENT ON COLUMN EMPLOYEE.HIRE_DATE IS '입사일';
COMMENT ON COLUMN EMPLOYEE.ENT_DATE IS '퇴사일';
COMMENT ON COLUMN EMPLOYEE.ENT_YN IS '퇴직여부';

INSERT INTO C##SERVER.EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, DEPT_CODE, JOB_CODE, SALARY, BONUS, MANAGER_ID, HIRE_DATE, ENT_DATE, ENT_YN)
VALUES ('200','선동일','621235-1985634','sun_di@KH.or.kr','01099546325','D9','J1',8000000,0.3,NULL,TO_DATE('1990-02-06','YYYY-MM-DD'),NULL,'N');

-- 추가 EMPLOYEE 데이터 삽입 생략 (위와 동일한 방식으로 적용)

--------------------------------------------------------
--  DDL for Table JOB
--------------------------------------------------------
CREATE TABLE JOB 
(
    JOB_CODE CHAR(2 BYTE) PRIMARY KEY, 
    JOB_NAME VARCHAR2(35 BYTE) NOT NULL
);

COMMENT ON COLUMN JOB.JOB_CODE IS '직급코드';
COMMENT ON COLUMN JOB.JOB_NAME IS '직급명';
COMMENT ON TABLE JOB IS '직급';

INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J1','대표');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J2','부사장');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J3','부장');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J4','차장');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J5','과장');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J6','대리');
INSERT INTO C##SERVER.JOB (JOB_CODE, JOB_NAME) VALUES ('J7','사원');

--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------
CREATE TABLE LOCATION 
(
    LOCAL_CODE CHAR(2 BYTE) PRIMARY KEY, 
    NATIONAL_CODE CHAR(2 BYTE) NOT NULL, 
    LOCAL_NAME VARCHAR2(40 BYTE) NOT NULL
);

COMMENT ON COLUMN LOCATION.LOCAL_CODE IS '지역코드';
COMMENT ON COLUMN LOCATION.NATIONAL_CODE IS '국가코드';
COMMENT ON COLUMN LOCATION.LOCAL_NAME IS '지역명';
COMMENT ON TABLE LOCATION IS '지역';

INSERT INTO C##SERVER.LOCATION (LOCAL_CODE, NATIONAL_CODE, LOCAL_NAME) VALUES ('L1','KO','ASIA1');
-- 추가 LOCATION 데이터 삽입 생략

--------------------------------------------------------
--  DDL for Table NATIONAL
--------------------------------------------------------
CREATE TABLE NATIONAL 
(
    NATIONAL_CODE CHAR(2 BYTE) PRIMARY KEY, 
    NATIONAL_NAME VARCHAR2(35 BYTE) NOT NULL
);

COMMENT ON COLUMN NATIONAL.NATIONAL_CODE IS '국가코드';
COMMENT ON COLUMN NATIONAL.NATIONAL_NAME IS '국가명';
COMMENT ON TABLE NATIONAL IS '국가';

INSERT INTO C##SERVER.NATIONAL (NATIONAL_CODE, NATIONAL_NAME) VALUES ('KO','한국');
-- 추가 NATIONAL 데이터 삽입 생략

--------------------------------------------------------
--  DDL for Table SAL_GRADE
--------------------------------------------------------
CREATE TABLE SAL_GRADE 
(
    SAL_LEVEL CHAR(2 BYTE) PRIMARY KEY, 
    MIN_SAL NUMBER NOT NULL, 
    MAX_SAL NUMBER NOT NULL
);

COMMENT ON COLUMN SAL_GRADE.SAL_LEVEL IS '급여등급';
COMMENT ON COLUMN SAL_GRADE.MIN_SAL IS '최소급여';
COMMENT ON COLUMN SAL_GRADE.MAX_SAL IS '최대급여';
COMMENT ON TABLE SAL_GRADE IS '급여등급';

INSERT INTO C##SERVER.SAL_GRADE (SAL_LEVEL, MIN_SAL, MAX_SAL) VALUES ('S1',6000000,10000000);
-- 추가 SAL_GRADE 데이터 삽입 생략

COMMIT;